:ruby: ree
:application: rails.momentum.agiletoolkit.com
:user: rails
:group: rails
:ssl:
:self_signed: true
:deploy_to: /srv/momentumdance
:domain: momentum.agiletoolkit.com
:repository: git@github.com:agiletoolkit/momentumdance.git
:shared_children:
- system
- log
- pids
- config
:apt_gems:
  :rails:    
  :paperclip:
  - imagemagick
:passenger:
  :max_pool_size: 3
  :use_global_queue: true
:mysql:
  :innodb_buffer_pool_size: 128M

